networks:
  counter-net:

volumes:
  counter-vol:
  
services:
  web-fe:
    build: .
    command: python app.py
    ports:
      - target: 8080
        published: 18080
    networks:
      counter-net:
    volumes:
      - type: volume
        source: counter-vol
        target: /app
    image: "alpine"
  redis:
    image: "redis:alpine"
    networks:
      counter-net:

